### ISSUE TITLE
Minor wording in step 5)

### ISSUE THREAD

**Issue by iankrigsman** [sethgoldin/install-davinci-resolve-centos#21]
Great instructions, thanks.

Step 5) says to perform an update and reboot.

I observed the command line to perform the update, but overlooked the _reboot_ ! This caused the remaining steps to be out of whack with the `$(uname -r)` reference and subsequent issues.

Can I suggest that `reboot` be added in code font after the update line just to be clear? This has been done elsewhere and is very helpful when stepping through the instructions.

Cheers

**Comment by sethgoldin** [comment]
Good catch. You're actually not the first person I've heard from who had missed the step. I've gone ahead and taken care of this: https://github.com/sethgoldin/install-davinci-resolve-centos/pull/22
