### ISSUE TITLE
Identifying broken grub in step 11)

### ISSUE THREAD

**Issue by iankrigsman** [sethgoldin/install-davinci-resolve-centos#23]
Thanks for addressing #21 so promptly.

One other (again minor) issue I encountered...

After rebooting at the end of step 11), I encountered the blank screen problem when attempting to log in. Now, you describe this in step 13), but at this point I think I've done something wrong and try to fix it before proceeding. A google search reveals that the `rhgb` parameter is the culprit. I got around this with a temporary `e` edit fix on the grub menu so I could boot (as per 13. ii.)

Suggestion:
At the end of step 11), a comment something like... "See Step 13 if you encounter a blank screen after login."
I know it sounds like stating the obvious (and the reader can be expected to be reasonably converse in Linux), but my brain tells me I can't proceed to the next step if something is not working.

Alternatively, if Steps 12 and 13 were swapped, that might read better anyway. In fact, I'm not sure if the DeckLink driver instructions can be done without the grub fix..?

Finally, the temporary edit fix you describe in 13. ii. is most useful, and obviates the need for other methods like SSH. Perhaps that could become sub-step i. and the grub rebuild sub-step ii. ?

This, and the reboot in step 5) were the only issues I had as a first-time user. Thanks once again for an excellent reference.

**Comment by sethgoldin** [comment]
Good feedback here. Going to put my head down and try to make some edits to make this all a bit clearer and easier.

**Comment by sethgoldin** [comment]
@iankrigsman I spend a little time cleaning all this up, here: https://github.com/sethgoldin/install-davinci-resolve-centos/tree/clarifying-broken-grub

I want to to take another look with fresh eyes in the morning, but would appreciate your thoughts before I merge the changes.

**Comment by iankrigsman** [comment]
Looks good to me!

**Comment by sethgoldin** [comment]
This is resolved: https://github.com/sethgoldin/install-davinci-resolve-centos/pull/24
