### ISSUE TITLE
Update 8.1 to 8.2

### ISSUE THREAD

**Issue by sethgoldin** [sethgoldin/install-davinci-resolve-centos#37]
CentOS 8.2.2004 has been released. It's time to update the CentOS 8 instructions to reflect 8.2.

**Comment by abrock** [comment]
Hi,

I did install CentOS 8.2 following these instructions. Thank you very much for providing them, I managed to get a working DaVinci Resolve installation with your help. While installing I wrote down a couple of things which might help updating the tutorial:

The Nvidia driver fails to build the kernel modules.
/var/log/nvidia-installer.log shows the problem:

`Cannot generate ORC metadata for CONFIG_UNWINDER_ORC=y, please install libelf-dev, libelf-devel or elfutils-libelf-devel".  Stop.`

I did this to fix the problem:

`sudo yum install elfutils-libelf-devel`

Then the Nvidia installer asked:

`An incomplete installation of libglvnd was found. All of the essential libglvnd libraries are present, but one or more optional components are missing. Do you want to install a full copy of libglvnd? This will overwrite any existing libglvnd libraries`

I thought letting the OS worry about installing libraries would be better than having the NVidia installer do it so I aborted the installation and manually installed those:
`sudo yum install libglvnd-devel libglvnd-core-devel`

Next time the question didn't appear.

About the GRUB configuration:

My file didn't contain the string "rhgb"

This was my complete file:
```
GRUB_TIMEOUT=5
GRUB_DISTRIBUTOR="$(sed 's, release .*$,,g' /etc/system-release)"
GRUB_DEFAULT=saved
GRUB_DISABLE_SUBMENU=true
GRUB_TERMINAL_OUTPUT="console"
GRUB_CMDLINE_LINUX="crashkernel=auto resume=/dev/mapper/cl-swap rd.lvm.lv=cl/root rd.lvm.lv=cl/swap"
GRUB_DISABLE_RECOVERY="true"
GRUB_ENABLE_BLSCFG=true
```


I simply appended `rd.driver.blacklist=nouveau` so the resulting line is:
```
GRUB_CMDLINE_LINUX="crashkernel=auto resume=/dev/mapper/cl-swap rd.lvm.lv=cl/root rd.lvm.lv=cl/swap rd.driver.blacklist=nouveau"
```

This worked, after re-building the GRUB configuration and rebooting I was greeted with a graphical interface and logging in and running `nvidia-smi` showed the expected output.

Additional question:
The NVidia installer asks if I want to install 32-bit compatibility libraries.
Do I need them? Can they get in the way? I selected "yes".

Thanks again for providing this handy installation guide, I'm pretty sure it saved me a lot of frustration.

**Comment by sethgoldin** [comment]
Thanks. ELRepo actually packages the NVIDIA driver now, so I plan on revising the 8.2 instructions to use that. See: https://github.com/sethgoldin/install-davinci-resolve-centos/issues/31

**Comment by sethgoldin** [comment]
Resolved with https://github.com/sethgoldin/install-davinci-resolve-centos/pull/40
