### ISSUE TITLE
Mini panel only works with root user.

### ISSUE THREAD

**Issue by alatteri** [sethgoldin/install-davinci-resolve-centos#39]
Hello,
I've installed CentOS 7.8 per the guidelines.  The Mini panel only works when launching Resolve as the root user.  Any other user, and it is not seen.   Any thoughts?

**Comment by sethgoldin** [comment]
Perhaps you created a non-admin user? Try either making the user an admin after the fact or reinstalling the OS again and making sure that the user you create is an admin.
