### ISSUE TITLE
Centos 8.2 install crashing after mesa-libGLU install

### ISSUE THREAD

**Issue by DarylMc** [sethgoldin/install-davinci-resolve-centos#42]
Hello Seth
Thanks for providing these instructions.
I followed them through and skipped step 12.
When I get to step 13 sudo dnf install mesa-libGLU and reboot the system halts during the reboot process.
I have tried several times.
Sorry that is not much information but do you have any idea what I should try next?

Ryzen9
X570 chipset
M2 PCI SSD's
2080TI graphics

**Comment by sethgoldin** [comment]
These notes were developed only from systems running Intel chips, which is what Blackmagic Design uses for their Linux development and testing. You may have to find some kind of equivalent package for your AMD chip. I have no experience with AMD chips.
