### ISSUE TITLE
Rocky Linux 8

### ISSUE THREAD

**Issue by alanmcseveney** [sethgoldin/install-davinci-resolve-centos#44]
@sethgoldin 

Do you see this being installable/workable on Rocky Linux 8 at any point soon? I got Resolve Studio 18 going on RL8, but the Thunderbolt UltraStudio 4K v2 just kernel panics the machine on connection.

Really just trying to get together an RL8 thin client for connecting to a AWS ec2 instance which will be running Resolve  Studio 18, and the thin client needs:
Resolve Mini Panel driver;
Davinci Remote Monitoring app;
UltraStudio 4K drivers;
Remote Desktop software (Parsec/PCoIP Client/DCV Client).

**Comment by sethgoldin** [comment]
I haven't played with it myself, but BMD posted their own AMI that might accomplish what you're going for: https://aws.amazon.com/blogs/media/blackmagic-design-advances-remote-davinci-resolve-workflows-with-aws/

Presumably they did the hard work of including a GUI and all the assorted drivers for the GPUs and other peripherals, so you might try spinning it up, and sort of picking it apart by examining what's installed.
